name: 'rushawx'
description: 'Golang Course by rushawx'
logo: 'assets/images/logo.png'
baseurl: '/golangCourse'
disqus: 'demowebsite'
email: 'rushawx@gmail.com'

include: ["_pages"]
permalink: /:title/

plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    rushawx:
      name:           rushawx
      display_name:   Anton Shishkov
      site:           https://www.rushawx.ghost.io
      avatar:         /assets/images/photo.jpg
      bio:            "Hi, I am Anton, the author of this Golang Course. I hope you like it!"
      email:          rushawx@gmail.com
      tg:             https://t.me/rushawx


defaults:

  - scope:
      path: "_posts"
    values:
      layout: post
      author: rushawx
      avatar: /assets/images/photo.jpg

  - scope:
      path: "_pages"
    values:
      layout: page

markdown: kramdown
highlighter: rouge

paginate: 10

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]